FROM postgres:16

# Copy certificates
COPY dev-certs/server.crt /var/lib/postgresql/certs/server.crt
COPY dev-certs/server.key /var/lib/postgresql/certs/server.key
COPY dev-certs/ca.crt /var/lib/postgresql/certs/ca.crt

# Set correct ownership and permissions
RUN chown postgres:postgres /var/lib/postgresql/certs/server.* /var/lib/postgresql/certs/ca.crt && \
    chmod 600 /var/lib/postgresql/certs/server.key && \
    chmod 644 /var/lib/postgresql/certs/server.crt /var/lib/postgresql/certs/ca.crt

# Configure PostgreSQL to use SSL
CMD ["postgres", \
     "-c", "ssl=on", \
     "-c", "ssl_cert_file=/var/lib/postgresql/certs/server.crt", \
     "-c", "ssl_key_file=/var/lib/postgresql/certs/server.key", \
     "-c", "ssl_ca_file=/var/lib/postgresql/certs/ca.crt"]

